title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://shuhabi-aot.github.io

aux_links:
  Template Repository: https://github.com/shuhabi-aot/demo-docs
